// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

// Di development (local): load dari .env.local
// Di production (Docker): env sudah diinjek oleh docker-compose, tidak perlu dotenv
if (process.env.NODE_ENV !== "production") {
  const { config } = await import("dotenv");
  config({ path: ".env.local" });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"] ?? "",
  },
});
